### PR TITLE
ptch: add x-upsert header to upsert duplicate object

### LINKED ISSUE #21: Support upsert functionality
More info - https://github.com/supabase/storage-js/issues/7

### PR DESCRIPTION
**Pull request by ankitjena**
## What kind of change does this PR introduce?

feature

## What is the current behavior?

Closes #21 
Currently insert throws a duplicate key error when trying to insert an key that already exists.

## What is the new behavior?

Adds a `x-upsert` header to the insert object api, which upserts the object when the value of the header is `true`.

### Screen recording
Peek 2021-06-20 11-59

### CODE REVIEW

**Comment by inian** [comment]
Hey Ankit, this looks good! 

There seems to be a [type error](https://github.com/supabase/storage-api/pull/32/files) and can you add tests for the upsert mode too?

**Comment by ankitjena** [comment]
> There seems to be a [type error](https://github.com/supabase/storage-api/pull/32/files) and can you add tests for the upsert mode too?

I think upgrading the `postgrest-js` should fix it. Adding tests for the upsert mode.

**Comment by inian** [comment]
> I think upgrading the postgrest-js should fix it.

Ah cool, lets upgrade postgrest-js also in this PR then.

**Comment by ankitjena** [comment]
> Ah cool, lets upgrade postgrest-js also in this PR then.

Should I upgrade it to the latest version, from the repo I see `v0.32.0`?

**Comment by inian** [comment]
Yup, that version should be fine. I don't think there were any breaking changes.

**Comment by ankitjena** [comment]
The tests are failing for some reason. Not related to the test suites though.

**Comment by inian** [comment]
I ran the tests locally and they seem to be fine @ankitjena. I will debug why the Github actions are failing separately. Thanks for your contribution ❤️

**Comment by ankitjena** [comment]
Also @inian Should I create a issue in `storage-js` repo to support this, for next steps

**Comment by inian** [comment]
Do you want to help with this too Ankit? https://github.com/supabase/storage-js/issues/7#issuecomment-864812487

**Comment by ankitjena** [comment]
> Do you want to help with this too Ankit? [supabase/storage-js#7 (comment)](https://github.com/supabase/storage-js/issues/7#issuecomment-864812487)

Sure do

**Pull request merged**
