### PR TITLE
feat: expose metrics endpoint

### PR DESCRIPTION
**Pull request by darora**

### CODE REVIEW

**Review by thebengeu — APPROVED** [review]

**Comment by thebengeu** [comment]
Fix tests?

**Comment by darora** [comment]
Having a hard time running them locally; keep getting `    error: password authentication failed for user "postgres"` for ~12 tests. Any suggestions? Using a vanilla `.env{,.test}`

**Comment by darora** [comment]
I can see why it might be failing (the app object is built multiple times, which doesn't happen in normal usage), I just can't test fixes to it

**Comment by darora** [comment]
Have a fix for the tests up.

The cleaner thing to do would be to just initialize the app once, though perhaps we're testing that things work as spec'ed across app initializations, so I've done the easier thing of using new registries each time.

**Comment by thebengeu** [comment]
I don't see why we shouldn't initialise the app once in tests when that's what's done in production, but this works too, maybe we could clean it up next time.

**Pull request merged**
