### PR TITLE
feat: add support for byte range requests

### PR DESCRIPTION
**Pull request by inian**
fixes https://github.com/supabase/storage-api/issues/20

Video and Audio files should play better now

### CODE REVIEW

**Comment by quicksnap** [comment]
Sweeeeet

**Comment by inian** [comment]
Will be deployed to prod next week :)

**Comment by quicksnap** [comment]
Does Supabase broadcast when production gets deployed?

**Comment by inian** [comment]
Hey @quicksnap, not at the moment. Usually happens in a week or two after new storage, realtime, gotrue versions are released.

**Pull request merged**
