### PR TITLE
Support for optional S3 credentials

### PR DESCRIPTION
**Pull request by scottymack**
## What kind of change does this PR introduce?

Feature

## What is the current behavior?

Unable to connect to non AWS S3 storage that requires the [Credentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html#credentials) object to be included in the `S3ClientConfig`.

## What is the new behavior?
Allow passing in `access key ID` and `secret access key` as optional environment variables and then include them as the `Credentials` object in the `S3ClientConfig` if present.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Review by bernardomichel — APPROVED** [review]

**Review by thebengeu — APPROVED** [review]

**Comment by scottymack** [comment]
Looks like we need approval for the workflow to run now @thebengeu

**Comment by thebengeu** [comment]
Approved, but looks like there are still conflicts?

**Comment by scottymack** [comment]
Looks like I forgot to run Prettier. Just did that

**Comment by inian** [comment]
Can't this be done by setting the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY env vars @scottymack? I don't think this needs to be explicitly handled in the code.

**Pull request closed without merging**
