### PR TITLE
set forcePathStyle when using S3 endpoint

### PR DESCRIPTION
**Pull request by mingfang**
fixes https://github.com/supabase/storage-api/issues/252

## What kind of change does this PR introduce?

enhancement

## What is the current behavior?

does not work with localstack or minio

## What is the new behavior?

now works with localstack and minio

### CODE REVIEW

**Comment by fenos** [comment]
can we make this a configuration option using an env variable?

maybe something like: `S3_FORCE_PATH_STYLE` - let's try it to keep it backwards compatible

**Comment by mingfang** [comment]
@fenos 
I added a new configuration called `GLOBAL_S3_FORCE_PATH_STYLE`

**Review by fenos — APPROVED** [review]

**Comment by mingfang** [comment]
@fenos please review

**Comment by fenos** [comment]
Thanks for the contribution @mingfang

**Pull request merged**
